create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  patient_id uuid not null unique references auth.users (id) on delete cascade,
  provider_id uuid references auth.users (id) on delete set null,
  next_follow_up_date date not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.follow_ups
  add column if not exists patient_id uuid references auth.users (id) on delete cascade,
  add column if not exists provider_id uuid references auth.users (id) on delete set null,
  add column if not exists next_follow_up_date date,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'follow_ups_patient_id_key'
      and conrelid = 'public.follow_ups'::regclass
  ) then
    alter table public.follow_ups
      add constraint follow_ups_patient_id_key unique (patient_id);
  end if;
end
$$;

create index if not exists follow_ups_next_follow_up_date_idx
on public.follow_ups (next_follow_up_date asc);

create index if not exists follow_ups_provider_id_idx
on public.follow_ups (provider_id);

alter table public.follow_ups enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'patients can view their own follow ups'
  ) then
    create policy "patients can view their own follow ups"
    on public.follow_ups
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'providers can view patient follow ups'
  ) then
    create policy "providers can view patient follow ups"
    on public.follow_ups
    for select
    to authenticated
    using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'providers can insert follow ups'
  ) then
    create policy "providers can insert follow ups"
    on public.follow_ups
    for insert
    to authenticated
    with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'providers can update follow ups'
  ) then
    create policy "providers can update follow ups"
    on public.follow_ups
    for update
    to authenticated
    using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider')
    with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'providers can delete follow ups'
  ) then
    create policy "providers can delete follow ups"
    on public.follow_ups
    for delete
    to authenticated
    using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider');
  end if;
end
$$;
