create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references auth.users (id) on delete cascade,
  alert_type text not null,
  title text not null,
  message text not null,
  vitals_created_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.alerts
  add column if not exists alert_type text,
  add column if not exists title text,
  add column if not exists message text,
  add column if not exists vitals_created_at timestamptz,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.vitals
  add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists alerts_patient_id_created_at_idx
on public.alerts (patient_id, created_at desc);

alter table public.alerts enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'alerts'
      and policyname = 'users can view their own alerts'
  ) then
    create policy "users can view their own alerts"
    on public.alerts
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'alerts'
      and policyname = 'authenticated users can insert their own alerts'
  ) then
    create policy "authenticated users can insert their own alerts"
    on public.alerts
    for insert
    to authenticated
    with check (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'alerts'
      and policyname = 'users can delete their own alerts'
  ) then
    create policy "users can delete their own alerts"
    on public.alerts
    for delete
    to authenticated
    using (auth.uid() = patient_id);
  end if;
end
$$;

create or replace function public.sync_alerts_from_latest_vitals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.alerts
  where patient_id = new.patient_id;

  if new.heart_rate > 120 then
    insert into public.alerts (
      patient_id,
      alert_type,
      title,
      message,
      vitals_created_at
    )
    values (
      new.patient_id,
      'high_heart_rate',
      'High heart rate alert',
      'Heart rate is above 120 bpm in the latest vitals entry.',
      new.created_at
    );
  end if;

  if new.systolic_bp > 180 then
    insert into public.alerts (
      patient_id,
      alert_type,
      title,
      message,
      vitals_created_at
    )
    values (
      new.patient_id,
      'high_blood_pressure',
      'High blood pressure alert',
      'Systolic blood pressure is above 180 mmHg in the latest vitals entry.',
      new.created_at
    );
  end if;

  if new.systolic_bp < 90 then
    insert into public.alerts (
      patient_id,
      alert_type,
      title,
      message,
      vitals_created_at
    )
    values (
      new.patient_id,
      'low_blood_pressure',
      'Low blood pressure alert',
      'Systolic blood pressure is below 90 mmHg in the latest vitals entry.',
      new.created_at
    );
  end if;

  return new;
end;
$$;

drop trigger if exists on_vitals_insert_sync_alerts on public.vitals;

create trigger on_vitals_insert_sync_alerts
after insert on public.vitals
for each row
execute function public.sync_alerts_from_latest_vitals();

with latest_vitals as (
  select distinct on (patient_id)
    patient_id,
    heart_rate,
    systolic_bp,
    created_at
  from public.vitals
  order by patient_id, created_at desc
),
generated_alerts as (
  select
    patient_id,
    created_at,
    'high_heart_rate' as alert_type,
    'High heart rate alert' as title,
    'Heart rate is above 120 bpm in the latest vitals entry.' as message
  from latest_vitals
  where heart_rate > 120

  union all

  select
    patient_id,
    created_at,
    'high_blood_pressure' as alert_type,
    'High blood pressure alert' as title,
    'Systolic blood pressure is above 180 mmHg in the latest vitals entry.' as message
  from latest_vitals
  where systolic_bp > 180

  union all

  select
    patient_id,
    created_at,
    'low_blood_pressure' as alert_type,
    'Low blood pressure alert' as title,
    'Systolic blood pressure is below 90 mmHg in the latest vitals entry.' as message
  from latest_vitals
  where systolic_bp < 90
)
insert into public.alerts (
  patient_id,
  alert_type,
  title,
  message,
  vitals_created_at
)
select
  generated_alerts.patient_id,
  generated_alerts.alert_type,
  generated_alerts.title,
  generated_alerts.message,
  generated_alerts.created_at
from generated_alerts
where not exists (
  select 1
  from public.alerts existing_alerts
  where existing_alerts.patient_id = generated_alerts.patient_id
    and existing_alerts.alert_type = generated_alerts.alert_type
    and existing_alerts.vitals_created_at = generated_alerts.created_at
);
