create table if not exists public.care_plans (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  description text not null,
  status text not null,
  next_review_date date,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.care_plans
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists status text,
  add column if not exists next_review_date date,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists care_plans_patient_id_created_at_idx
on public.care_plans (patient_id, created_at desc);

alter table public.care_plans enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'care_plans'
      and policyname = 'users can view their own care plans'
  ) then
    create policy "users can view their own care plans"
    on public.care_plans
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'care_plans'
      and policyname = 'authenticated users can insert their own care plans'
  ) then
    create policy "authenticated users can insert their own care plans"
    on public.care_plans
    for insert
    to authenticated
    with check (auth.uid() = patient_id);
  end if;
end
$$;
