create table if not exists public.medication_adherence (
  id bigint generated by default as identity primary key,
  medication_id bigint not null references public.medications (id) on delete cascade,
  patient_id uuid not null references auth.users (id) on delete cascade,
  taken_on date not null,
  taken_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  unique (medication_id, taken_on)
);

create index if not exists medication_adherence_patient_date_idx
on public.medication_adherence (patient_id, taken_on desc);

alter table public.medication_adherence enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'medication_adherence'
      and policyname = 'users can view their own medication adherence'
  ) then
    create policy "users can view their own medication adherence"
    on public.medication_adherence
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'medication_adherence'
      and policyname = 'authenticated users can insert their own medication adherence'
  ) then
    create policy "authenticated users can insert their own medication adherence"
    on public.medication_adherence
    for insert
    to authenticated
    with check (auth.uid() = patient_id);
  end if;
end
$$;
