create table if not exists public.medications (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references auth.users (id) on delete cascade,
  medication_name text,
  dosage text,
  frequency text,
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.medications
  add column if not exists medication_name text,
  add column if not exists dosage text,
  add column if not exists frequency text,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists medications_patient_id_created_at_idx
on public.medications (patient_id, created_at desc);

alter table public.medications enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'medications'
      and policyname = 'users can view their own medications'
  ) then
    create policy "users can view their own medications"
    on public.medications
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'medications'
      and policyname = 'authenticated users can insert their own medications'
  ) then
    create policy "authenticated users can insert their own medications"
    on public.medications
    for insert
    to authenticated
    with check (auth.uid() = patient_id);
  end if;
end
$$;
