create table if not exists public.follow_ups (
  id bigint generated by default as identity primary key,
  patient_id uuid not null unique references auth.users (id) on delete cascade,
  provider_id uuid not null references auth.users (id) on delete cascade,
  next_follow_up_date date not null,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists follow_ups_next_follow_up_date_idx
on public.follow_ups (next_follow_up_date asc);

alter table public.follow_ups enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'patients can view their own follow ups'
  ) then
    create policy "patients can view their own follow ups"
    on public.follow_ups
    for select
    to authenticated
    using (auth.uid() = patient_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'follow_ups'
      and policyname = 'providers can manage follow ups'
  ) then
    create policy "providers can manage follow ups"
    on public.follow_ups
    for all
    to authenticated
    using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider')
    with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'provider');
  end if;
end
$$;
